git:
  clone:
    - git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
source:
  - "$HOME/.homesick/repos/homeshick/homeshick.sh"
rm:
  - -rf $HOME/git
homeshick:
  clone:
    - https://github.com/git/git.git --batch
    - https://github.com/rbuchss/terminator.git --batch
    - https://github.com/rbuchss/vim-4-eva.git --batch
  link:
    - terminator --force
    - vim-4-eva --force
ln:
  - -s -f $HOME/.homesick/repos/git $HOME/git
